project_id = "bbfzfgcdioewzbmlgaqy"

[functions.analyze-image]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.analyze-request]
verify_jwt = false

[functions.analyze-template]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.moneroo-webhook]
verify_jwt = false

[functions.fedapay-webhook]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false
